### ISSUE TITLE
[Bug Report] Crash on draft page when draft has no fingerprints

### ISSUE THREAD

**Issue by WithoutPants** [stashapp/stash-box#527]
**Describe the bug**

UI crashes when viewing a scene draft that was submitted without fingerprints.

**To Reproduce**
Submit a scene draft without any fingerprints (not sure if this is the root issue or not), then view the draft in the UI. Blank page is shown with the following console error:

```
parse.ts:72 Uncaught TypeError: Cannot read properties of undefined (reading 'duration')
    at eDe (parse.ts:72:39)
    at tDe (SceneDraft.tsx:68:36)
    at GN (react-dom.production.min.js:157:137)
    at l6 (react-dom.production.min.js:267:460)
    at a6 (react-dom.production.min.js:250:347)
    at lz (react-dom.production.min.js:250:278)
    at hc (react-dom.production.min.js:250:138)
    at Ab (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at e.unstable_runWithPriority (scheduler.production.min.js:18:343)
```

Looking at the code, it's assuming there is at least one fingerprint to calculate the duration with. 

**Expected behavior**

Not sure if we should prevent submitting a draft without fingerprints, or if the UI should handle drafts without fingerprints.

**Comment by peolic** [comment]
I think it was already fixed with #507, it just wasn't released yet.
