### ISSUE TITLE
[BUG] Create scene and create studio page broken at 8833c7b

### ISSUE THREAD

**Issue by aghoulcoder** [stashapp/stash-box#645]
## Problem
Create scene and create studio page broken at 8833c7b

## To reproduce
1. Build stash-box from `master` or on commit 8833c7b
2. Run it
3. Go to http://localhost:9998/scenes/add
4. Page doesn't render. Console shows this:

```
react-dom.production.min.js:189 TypeError: The value of note could not be cast to a value that satisfies the schema type: "string". 

attempted value: undefined 

    at u8.cast (index.esm.js:617:13)
    at m8._cast (index.esm.js:1683:15)
    at m8.cast (index.esm.js:610:33)
    at SceneForm.tsx:106:33
    at Object.useMemo (react-dom.production.min.js:184:189)
    at qe.useMemo (react.production.min.js:25:208)
    at Sy (SceneForm.tsx:105:46)
    at tE (react-dom.production.min.js:167:137)
    at x4 (react-dom.production.min.js:290:337)
    at S4 (react-dom.production.min.js:280:389)
a1 @ react-dom.production.min.js:189
t.callback @ react-dom.production.min.js:189
bC @ react-dom.production.min.js:144
MC @ react-dom.production.min.js:262
v4 @ react-dom.production.min.js:260
EU @ react-dom.production.min.js:259
TU @ react-dom.production.min.js:283
Us @ react-dom.production.min.js:281
UC @ react-dom.production.min.js:273
ws @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:267
index.esm.js:617 Uncaught TypeError: The value of note could not be cast to a value that satisfies the schema type: "string". 

attempted value: undefined 

    at u8.cast (index.esm.js:617:13)
    at m8._cast (index.esm.js:1683:15)
    at m8.cast (index.esm.js:610:33)
    at SceneForm.tsx:106:33
    at Object.useMemo (react-dom.production.min.js:184:189)
    at qe.useMemo (react.production.min.js:25:208)
    at Sy (SceneForm.tsx:105:46)
    at tE (react-dom.production.min.js:167:137)
    at x4 (react-dom.production.min.js:290:337)
    at S4 (react-dom.production.min.js:280:389)
cast @ index.esm.js:617
_cast @ index.esm.js:1683
cast @ index.esm.js:610
(anonymous) @ SceneForm.tsx:106
useMemo @ react-dom.production.min.js:184
qe.useMemo @ react.production.min.js:25
Sy @ SceneForm.tsx:105
tE @ react-dom.production.min.js:167
x4 @ react-dom.production.min.js:290
S4 @ react-dom.production.min.js:280
CU @ react-dom.production.min.js:280
Zh @ react-dom.production.min.js:280
g1 @ react-dom.production.min.js:271
UC @ react-dom.production.min.js:273
ws @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:267
```
## Additional notes
8833c7b is the *first* bad commit.

**Comment by Maista6969** [comment]
Thanks for identifying the bad commit! I've [submitted a PR](https://github.com/stashapp/stash-box/pull/647) with a fix

edit: reset my fork, recreated PR
